# Generated by Django 5.0.9 on 2026-07-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="categories/")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers display first on the homepage.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this category everywhere on the site.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="categories__is_acti_350a72_idx",
                    )
                ],
            },
        ),
    ]
