# Generated by Django 5.0.9 on 2026-07-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="AFC - Ahmad Foods", max_length=150),
                ),
                (
                    "tagline",
                    models.CharField(default="Sweets & Bakers", max_length=150),
                ),
                (
                    "restaurant_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "restaurant_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "delivery_radius_km",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_address", models.CharField(blank=True, max_length=255)),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Mon-Sun: 9:00 AM - 11:00 PM",
                        max_length=255,
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/")),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
    ]
