# Generated by Django 5.0.9 on 2026-07-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("chef", "Chef"),
                            ("manager", "Manager"),
                            ("staff", "Staff"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "custom_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional — overrides the display label, e.g. 'Head Pastry Chef'.",
                        max_length=100,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="team/")),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
